version: '1'

services:
  backend:
    container_name: backend-app
    image: backend-app:1.0
    environment:
      - NODE_ENV=docker
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000

  frontend:
    container_name: frontend-app
    image: frontend-app:1.0
    environment:
      - NODE_ENV=docker
      - REACT_APP_API_BASE_URL=http://backend:5000
      
    build: 
      context: frontend
      dockerfile: Dockerfile
    ports:
     - 3100:3000
    depends_on:
     - backend
